language: node_js
node_js: stable
branchs:
  only:
  - develop
  - master
  - release
before_script:
  npm update -g npm
install:
- npm install
script:
# - npm test
- npm run build
deploy:
  provider: script
  script: deploy.sh