language: node_js
node_js: stable
branchs:
  only:
  - develop
  - master
  - release
before_script:
  npm update -g npm
cache:
  directories:
  - node_modules
script:
# - npm test
- npm install
- npm run build
deploy:
  provider: script
  script: chmod +x ./deploy.sh && bash ./deploy.sh
  on: 
    branch: master