language: node_js
node_js: stable
branchs:
  only:
  - develop
  - master
  - release
before_script:
  npm update -g npm
cache:
  directories:
  - node_modules
script:
# - npm test
- npm install
- npm run build
before_deploy:
  - 'curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"'
  - 'unzip awscli-bundle.zip'
  - './awscli-bundle/install -b ~/bin/aws'
  - 'export PATH=~/bin:$PATH'
deploy:
  provider: script
  script: chmod +x ./deploy.sh && bash ./deploy.sh
  skip_cleanup: true
  on: 
    branch: master